import type {
  ArtifactSummary,
  ChangeSetRow,
  CommandDefinition,
  CommandRunState,
  GateCategory,
  RequirementDetail,
  RequirementRow,
  RequirementSummary,
  TerminologyBrowserModel,
} from "./types";

export const appShellDefault: ArtifactSummary = {
  scope: "harness",
  generatedAt: "2026-06-10T14:25:52.986Z",
  missing: false,
  stale: false,
  staleSources: [],
  autoRefresh: "idle",
};

export const appShellMissing: ArtifactSummary = {
  ...appShellDefault,
  generatedAt: null,
  missing: true,
};

export const appShellStale: ArtifactSummary = {
  ...appShellDefault,
  stale: true,
  staleSources: ["harness/docs/requirements/REQ-030-harness-ui-app-shell.md"],
};

export const requirementRows: RequirementRow[] = [
  {
    id: "REQ-030",
    title: "하네스 UI 앱셸",
    traceState: "RED",
    cardStatus: "초안",
    productArea: "harness",
    priority: "높음",
    specRole: "원자 요건",
    parentRequirementIds: [],
    childRequirementIds: [],
    relatedRequirementIds: ["REQ-029"],
  },
  {
    id: "REQ-031",
    title: "하네스 UI 요건 추적 보드",
    traceState: "RED",
    cardStatus: "초안",
    productArea: "harness",
    priority: "높음",
    specRole: "원자 요건",
    parentRequirementIds: [],
    childRequirementIds: [],
    relatedRequirementIds: ["REQ-029", "REQ-030"],
  },
  {
    id: "REQ-010",
    title: "통합 하네스 게이트",
    traceState: "BLUE",
    cardStatus: "승인",
    productArea: "harness",
    priority: "높음",
    specRole: "원자 요건",
    parentRequirementIds: [],
    childRequirementIds: [],
    relatedRequirementIds: [],
  },
  {
    id: "REQ-028",
    title: "단계 인식 TDD 워크플로우",
    traceState: "BLUE",
    cardStatus: "승인",
    productArea: "harness",
    priority: "중간",
    specRole: "원자 요건",
    parentRequirementIds: [],
    childRequirementIds: [],
    relatedRequirementIds: [],
  },
  {
    id: "REQ-021",
    title: "개인별 할 일 관리",
    traceState: "BLUE",
    cardStatus: "승인",
    productArea: "todo",
    priority: "높음",
    specRole: "상위 요건",
    parentRequirementIds: [],
    childRequirementIds: ["REQ-022", "REQ-023", "REQ-024", "REQ-025", "REQ-027"],
    relatedRequirementIds: ["REQ-022", "REQ-023", "REQ-024", "REQ-025", "REQ-027", "REQ-026", "REQ-004", "REQ-011"],
  },
  {
    id: "REQ-022",
    title: "할 일 생성",
    traceState: "BLUE",
    cardStatus: "승인",
    productArea: "todo",
    priority: "높음",
    specRole: "원자 요건",
    parentRequirementIds: ["REQ-021"],
    childRequirementIds: [],
    relatedRequirementIds: ["REQ-021", "REQ-004", "REQ-015"],
  },
  {
    id: "REQ-023",
    title: "할 일 목록 조회",
    traceState: "BLUE",
    cardStatus: "승인",
    productArea: "todo",
    priority: "높음",
    specRole: "원자 요건",
    parentRequirementIds: ["REQ-021"],
    childRequirementIds: [],
    relatedRequirementIds: ["REQ-021", "REQ-004", "REQ-011", "REQ-015"],
  },
];

export const requirementSummary: RequirementSummary[] = [
  { state: "RED", count: 7 },
  { state: "GREEN", count: 0 },
  { state: "BLUE", count: 7 },
  { state: "INACTIVE", count: 0 },
];

export const terminologyBrowser: TerminologyBrowserModel = {
  scope: "harness",
  generatedAt: "2026-06-12T01:14:02.243Z",
  terms: [
    {
      key: "harness.standardTerm",
      domain: "harness",
      status: "approved",
      sourceFile: "harness/docs/terminology/domains/harness.json",
      ko: "표준 용어",
      en: "standard term",
      meaning: "하네스 용어 사전에 등록되어 카드, 시나리오, 코드 식별자, 검사 결과에서 같은 의미로 쓰는 term key와 그 정의.",
      allow: ["용어", "term", "term key", "표준어"],
      ban: [],
      names: {
        json: ["terms", "terminology"],
      },
      reason: "요건 작성과 코드 검증에서 사용하는 용어 사전 항목을 UI와 문서에서 같은 의미로 추적하기 위해 표준 용어로 사용한다.",
    },
    {
      key: "harness.requirementCard",
      domain: "harness",
      status: "approved",
      sourceFile: "harness/docs/terminology/domains/harness.json",
      ko: "요건 카드",
      en: "requirement card",
      meaning: "REQ-XXX 단위로 사용자 요구사항, 범위, 수용 기준, 의사결정을 한 곳에 적은 사람 검토 산출물.",
      allow: ["카드"],
      ban: [],
      names: {
        json: ["requirementCard", "requirements"],
      },
    },
    {
      key: "harness.traceState",
      domain: "harness",
      status: "approved",
      sourceFile: "harness/docs/terminology/domains/harness.json",
      ko: "추적 상태",
      en: "trace state",
      meaning: "요건의 수용 기준, 연결 산출물, 테스트 결과를 바탕으로 RED/GREEN/BLUE/INACTIVE 중 하나로 표시되는 추적 판정.",
      allow: ["추적 판정", "요건 추적 상태"],
      ban: [],
      names: {
        json: ["traceState"],
        field: ["traceState"],
      },
    },
    {
      key: "ui.appShell",
      domain: "ui",
      status: "approved",
      sourceFile: "harness/docs/terminology/domains/ui.json",
      ko: "앱셸",
      en: "app shell",
      meaning: "프런트엔드 애플리케이션의 첫 화면에서 공통 기반과 주요 진입점을 제공하는 화면 골격이다.",
      allow: ["앱 셸", "애플리케이션 셸"],
      ban: [],
      names: {
        java: [],
      },
      reason: "프런트엔드 기반 요건에서 앱 진입 화면을 추적하기 위해 표준 용어로 사용한다.",
    },
    {
      key: "ui.dialog",
      domain: "ui",
      status: "approved",
      sourceFile: "harness/docs/terminology/domains/ui.json",
      ko: "대화상자",
      en: "dialog",
      meaning: "사용자 작업을 위해 화면 위에 겹쳐 띄우는 모드형 표시 영역. 입력을 받는 입력 대화상자와 동작을 확인하는 확인 대화상자를 포함한다.",
      allow: ["확인 대화상자", "입력 대화상자"],
      ban: ["다이얼로그", "모달", "팝업", "확인창", "폼 대화상자"],
      names: {},
      note: "본문 어휘 통제용 등록이다. 카드 표준 용어 사용은 UI primitive deny-list가 차단한다.",
      reason: "요건 본문에서 대화상자 표현을 정규화하고 별칭 혼용을 막기 위해 등록한다.",
    },
    {
      key: "todo.dueDate",
      domain: "todo",
      status: "draft",
      sourceFile: "harness/docs/terminology/draft.json",
      ko: "마감일",
      en: "due date",
      meaning: "할 일 항목에 선택적으로 지정하는 완료 목표 날짜.",
      allow: ["기한"],
      ban: ["데드라인"],
      names: {
        field: ["dueDate"],
        json: ["dueDate"],
      },
      note: "승인 전 후보 용어 예시다.",
    },
  ],
};

export const requirementDetail: RequirementDetail = {
  id: "REQ-031",
  title: "하네스 UI 요건 추적 보드",
  cardStatus: "초안",
  priority: "높음",
  targetSystem: "harness",
  productArea: "harness",
  verificationLevel: "mixed",
  traceState: "RED",
  sourceFile: {
    kind: "card",
    file: "harness/docs/requirements/REQ-031-harness-ui-requirement-board.md",
    line: 1,
  },
  purpose: "하네스 작업자는 선택한 범위의 모든 요건이 어떤 추적 상태(RED/GREEN/BLUE/INACTIVE)와 카드 상태에 있는지 한 화면에서 파악하고, 작업할 요건을 골라 상세로 들어갈 수 있어야 한다.",
  scopeItems: [
    "요건 보드는 선택한 범위의 추적 산출물에 있는 모든 요건을 목록형 카드로 표시한다.",
    "목록형 카드의 각 항목은 요건 ID, 제목, 카드 상태, 제품 영역, 우선순위, 명세 역할, 상위 요건 ID, 하위 요건 수를 한 줄에 표시하고, 카드 상태, 제품 영역, 우선순위는 제목 바로 오른쪽에 접두 문자 없는 종류별 색상의 작은 뱃지로 표시하며, 추적 상태 뱃지는 우측 끝에 배치한다.",
    "하위 요건 카드는 좌측 들여쓰기와 세로선으로 하위 관계를 시각적으로 구분한다.",
    "보드 상단에 추적 상태별 요건 수 요약을 표시한다.",
    "제목 검색어, 추적 상태, 카드 상태, 제품 영역으로 목록을 좁힐 수 있고 필터 상태는 URL query에 반영된다.",
    "목록에서 요건 ID를 선택하면 현재 필터 query를 유지한 채 해당 요건의 상세 화면 route로 이동한다.",
  ],
  terms: [
    { key: "harness.requirementCard", ko: "요건 카드", en: "requirement card" },
    { key: "harness.scope", ko: "범위", en: "scope" },
    { key: "harness.validationArtifact", ko: "검증 산출물", en: "validation artifact" },
    { key: "harness.traceState", ko: "추적 상태", en: "trace state" },
  ],
  outOfScopeItems: [
    "요건 카드 본문 편집. 조회 전용이다.",
    "추적 상태 재계산. 추적 산출물의 판정 값을 그대로 표시한다.",
    "시간 흐름에 따른 상태 변화 이력 표시.",
  ],
  decisionLogs: [
    {
      date: "2026-06-10",
      decision: "보드의 추적 상태는 추적 산출물(trace state)의 판정 값을 그대로 표시하고 화면이나 서버가 재계산하지 않는다.",
      reason: "REQ-010 단일 게이트 원칙. 판정이 둘이 되면 CLI와 UI가 다른 답을 줄 수 있다.",
      decisionMaker: "REDSTONE",
      impact: "산출물이 없거나 오래된 경우의 안내는 REQ-030 앱셸의 신선도 표시가 담당한다.",
    },
    {
      date: "2026-06-12",
      decision: "요건 보드는 표가 아니라 목록형 카드로 표시하고, 계층 정보는 명세 역할, 상위 요건 ID, 하위 요건 수로 축약한다.",
      reason: "상위/하위 관계는 작업 영향 범위 판단에 필요하지만, 전체 관련 요건 목록을 보드에 펼치면 목록 스캔성이 떨어진다.",
      decisionMaker: "REDSTONE",
      impact: "하위 요건은 좌측 들여쓰기와 세로선으로 구분하고, 상세한 관련 요건 검토는 요건 상세 화면이 담당한다.",
    },
    {
      date: "2026-06-12",
      decision: "요건 보드 목록 카드는 요건 ID와 제목을 한 줄에 두고 추적 상태 뱃지를 우측 끝에 배치하는 밀도 높은 형식으로 표시한다.",
      reason: "요건 수가 많을 때 카드 높이가 커지면 보드의 스캔성과 비교성이 떨어진다.",
      decisionMaker: "REDSTONE",
      impact: "카드 상태, 제품 영역, 우선순위는 제목 바로 오른쪽에 접두 문자 없는 종류별 색상의 작은 뱃지로 유지하고, 긴 제목은 한 줄 말줄임으로 처리한다. 보드 카드 높이는 보조 줄 없이 한 줄 기준으로 맞춘다.",
    },
    {
      date: "2026-06-12",
      decision: "요건 보드 필터는 URL query로 보존하고 상세 이동 시 query를 유지한다.",
      reason: "상세를 확인한 뒤 목록으로 돌아올 때 사용자가 좁혀 둔 작업 맥락이 사라지면 탐색 비용이 커진다.",
      decisionMaker: "REDSTONE",
      impact: "상세 화면의 목록 복귀 버튼은 상세 route의 query를 유지한 /requirements로 이동한다.",
    },
  ],
  acceptanceCriteria: [
    {
      id: "AC-1",
      text: "요건 보드는 선택한 범위의 모든 요건을 요건 ID, 제목, 카드 상태, 제품 영역, 우선순위, 명세 역할, 상위 요건 ID, 하위 요건 수가 한 줄에 있고 추적 상태 뱃지가 우측 끝에 있는 목록형 카드로 표시하며, 카드 상태, 제품 영역, 우선순위는 제목 바로 오른쪽에 접두 문자 없는 종류별 색상의 작은 뱃지로 표시한다",
      channel: "UI",
      status: "MISSING",
      file: "harness/docs/requirements/REQ-031-harness-ui-requirement-board.md",
      line: 44,
      scenarios: ["요건 보드는 선택한 범위의 요건과 계층 구조, 상태 요약을 보여준다"],
    },
    {
      id: "AC-2",
      text: "하위 요건 카드는 좌측 들여쓰기와 세로선으로 하위 관계가 구분된다",
      channel: "UI",
      status: "MISSING",
      file: "harness/docs/requirements/REQ-031-harness-ui-requirement-board.md",
      line: 45,
      scenarios: ["요건 보드는 선택한 범위의 요건과 계층 구조, 상태 요약을 보여준다"],
    },
    {
      id: "AC-3",
      text: "보드 상단에 추적 상태별 요건 수 요약이 표시된다",
      channel: "UI",
      status: "MISSING",
      file: "harness/docs/requirements/REQ-031-harness-ui-requirement-board.md",
      line: 46,
      scenarios: ["요건 보드는 선택한 범위의 요건과 계층 구조, 상태 요약을 보여준다"],
    },
    {
      id: "AC-4",
      text: "제목 검색어, 추적 상태, 카드 상태, 제품 영역으로 목록을 좁힐 수 있고 필터 상태는 URL query에 반영된다",
      channel: "UI",
      status: "MISSING",
      file: "harness/docs/requirements/REQ-031-harness-ui-requirement-board.md",
      line: 47,
      scenarios: ["보드 필터는 작업자가 볼 요건을 좁힌다"],
    },
    {
      id: "AC-5",
      text: "목록에서 요건 ID를 선택하면 현재 필터 query를 유지한 채 그 요건의 상세 화면 route로 이동한다",
      channel: "UI",
      status: "MISSING",
      file: "harness/docs/requirements/REQ-031-harness-ui-requirement-board.md",
      line: 48,
      scenarios: ["보드 항목에서 요건 상세로 이동한다"],
    },
    {
      id: "AC-6",
      text: "하네스 UI 서버가 제공하는 요건 추적 데이터는 추적 산출물의 판정 값과 일치한다",
      channel: "STATIC",
      status: "MISSING",
      file: "harness/docs/requirements/REQ-031-harness-ui-requirement-board.md",
      line: 49,
      scenarios: ["UI 서버가 제공하는 보드 데이터는 추적 산출물과 같은 판정을 가진다"],
    },
  ],
  scenarios: [
    {
      title: "요건 보드는 선택한 범위의 요건과 계층 구조, 상태 요약을 보여준다",
      status: "정의됨",
      file: "harness/docs/scenarios/REQ-031-harness-ui-requirement-board.feature",
      line: 4,
      covers: [
        "요건 보드는 선택한 범위의 모든 요건을 요건 ID, 제목, 카드 상태, 제품 영역, 우선순위, 명세 역할, 상위 요건 ID, 하위 요건 수가 한 줄에 있고 추적 상태 뱃지가 우측 끝에 있는 목록형 카드로 표시하며, 카드 상태, 제품 영역, 우선순위는 제목 바로 오른쪽에 접두 문자 없는 종류별 색상의 작은 뱃지로 표시한다",
        "하위 요건 카드는 좌측 들여쓰기와 세로선으로 하위 관계가 구분된다",
        "보드 상단에 추적 상태별 요건 수 요약이 표시된다",
      ],
      steps: [
        "Given 선택한 범위의 추적 산출물에 상위 요건과 하위 원자 요건이 들어 있다",
        "When 하네스 작업자가 요건 보드를 연다",
        "Then 모든 요건이 요건 ID와 제목이 한 줄에 있는 목록형 카드로 보인다",
        "And 각 카드의 카드 상태, 제품 영역, 우선순위는 제목 바로 오른쪽에 접두 문자 없는 종류별 색상의 작은 뱃지로 보인다",
        "And 각 카드의 추적 상태 뱃지는 카드 우측 끝에 보인다",
        "And 각 카드의 명세 역할, 상위 요건 ID, 하위 요건 수는 같은 줄의 구조 뱃지로 함께 보인다",
        "And 하위 요건 카드는 좌측 들여쓰기와 세로선으로 하위 관계가 구분된다",
        "And 보드 상단에 추적 상태별 요건 수 요약이 보인다",
      ],
    },
    {
      title: "보드 필터는 작업자가 볼 요건을 좁힌다",
      status: "정의됨",
      file: "harness/docs/scenarios/REQ-031-harness-ui-requirement-board.feature",
      line: 19,
      covers: ["제목 검색어, 추적 상태, 카드 상태, 제품 영역으로 목록을 좁힐 수 있고 필터 상태는 URL query에 반영된다"],
      steps: [
        "Given 요건 보드에 서로 다른 제목, 추적 상태, 카드 상태, 제품 영역의 요건들이 보인다",
        "When 하네스 작업자가 제목 검색어와 추적 상태, 카드 상태, 제품 영역 필터를 적용한다",
        "Then 목록에는 필터 조건에 맞는 요건만 남는다",
        "And URL query에 필터 조건이 반영된다",
      ],
    },
    {
      title: "보드 항목에서 요건 상세로 이동한다",
      status: "정의됨",
      file: "harness/docs/scenarios/REQ-031-harness-ui-requirement-board.feature",
      line: 27,
      covers: ["목록에서 요건 ID를 선택하면 현재 필터 query를 유지한 채 그 요건의 상세 화면 route로 이동한다"],
      steps: [
        "Given 하네스 작업자가 필터가 적용된 요건 보드에서 요건 목록을 보고 있다",
        "When 목록 카드에서 하나의 요건 ID를 선택한다",
        "Then 선택한 요건의 상세 화면 route로 이동한다",
        "And 상세 화면 route에는 기존 필터 query가 유지된다",
      ],
    },
    {
      title: "UI 서버가 제공하는 보드 데이터는 추적 산출물과 같은 판정을 가진다",
      status: "정의됨",
      file: "harness/docs/scenarios/REQ-031-harness-ui-requirement-board.feature",
      line: 35,
      covers: ["하네스 UI 서버가 제공하는 요건 추적 데이터는 추적 산출물의 판정 값과 일치한다"],
      steps: [
        "Given 추적 산출물에 요건별 판정 값이 기록되어 있다",
        "When 하네스 UI 서버가 요건 추적 데이터를 제공한다",
        "Then 각 요건의 판정 값은 추적 산출물의 판정 값과 일치한다",
      ],
    },
  ],
  coverage: [
    {
      criterion: "요건 보드는 선택한 범위의 모든 요건을 요건 ID, 제목, 카드 상태, 제품 영역, 우선순위, 명세 역할, 상위 요건 ID, 하위 요건 수가 한 줄에 있고 추적 상태 뱃지가 우측 끝에 있는 목록형 카드로 표시하며, 카드 상태, 제품 영역, 우선순위는 제목 바로 오른쪽에 접두 문자 없는 종류별 색상의 작은 뱃지로 표시한다",
      channel: "UI",
      status: "MISSING",
      tests: [],
      scenarios: ["요건 보드는 선택한 범위의 요건과 계층 구조, 상태 요약을 보여준다"],
    },
    {
      criterion: "하위 요건 카드는 좌측 들여쓰기와 세로선으로 하위 관계가 구분된다",
      channel: "UI",
      status: "MISSING",
      tests: [],
      scenarios: ["요건 보드는 선택한 범위의 요건과 계층 구조, 상태 요약을 보여준다"],
    },
    {
      criterion: "보드 상단에 추적 상태별 요건 수 요약이 표시된다",
      channel: "UI",
      status: "MISSING",
      tests: [],
      scenarios: ["요건 보드는 선택한 범위의 요건과 계층 구조, 상태 요약을 보여준다"],
    },
    {
      criterion: "제목 검색어, 추적 상태, 카드 상태, 제품 영역으로 목록을 좁힐 수 있고 필터 상태는 URL query에 반영된다",
      channel: "UI",
      status: "MISSING",
      tests: [],
      scenarios: ["보드 필터는 작업자가 볼 요건을 좁힌다"],
    },
    {
      criterion: "목록에서 요건 ID를 선택하면 현재 필터 query를 유지한 채 그 요건의 상세 화면 route로 이동한다",
      channel: "UI",
      status: "MISSING",
      tests: [],
      scenarios: ["보드 항목에서 요건 상세로 이동한다"],
    },
    {
      criterion: "하네스 UI 서버가 제공하는 요건 추적 데이터는 추적 산출물의 판정 값과 일치한다",
      channel: "STATIC",
      status: "MISSING",
      tests: [],
      scenarios: ["UI 서버가 제공하는 보드 데이터는 추적 산출물과 같은 판정을 가진다"],
    },
  ],
  redReasons: [
    {
      ruleId: "TRACE-AC-MISSING",
      severity: "error",
      requirement: "REQ-031",
      file: "harness/docs/requirements/REQ-031-harness-ui-requirement-board.md",
      message: "요건 추적 보드 UI 테스트가 아직 연결되지 않았다.",
      evidence: "requiredChecks ui=MISSING",
      recommendation: "harness/ui Storybook Vitest story 테스트를 작성한다.",
    },
  ],
  blueBlockedBy: ["요건 카드 상태가 승인 아님: 초안"],
  linkedArtifacts: [
    {
      kind: "scenario",
      file: "harness/docs/scenarios/REQ-031-harness-ui-requirement-board.feature",
      line: 1,
    },
  ],
  // 하네스 요건은 백엔드 표면(API/DTO/JPA 엔티티)을 갖지 않는다. 라이브 buildRequirementDetailModel과
  // 같은 채움 규칙을 지키기 위해 셋 다 빈 배열로 둔다. 백엔드 표면 검토는 appRequirementDetail이 담당한다.
  apiSurfaces: [],
  dataShapes: [],
  entitySurfaces: [],
  uiSurfaces: [
    {
      kind: "Page",
      name: "RequirementBoardPage",
      route: "/requirements",
      status: "설계",
      description: "요건 목록과 상태 요약을 보여주는 하네스 UI 화면 표면이다.",
      file: "harness/ui/src/features/requirements/RequirementBoardPage.tsx",
      line: 1,
    },
    {
      kind: "Story",
      name: "RequirementBoard",
      status: "검토 가능",
      description: "요건 보드 UI 설계를 Storybook에서 검토하는 대표 상태다.",
      file: "harness/ui/src/features/requirements/RequirementBoard.stories.tsx",
      line: 1,
      storybookTitle: "Harness/Requirements/RequirementBoard",
      storybookStory: "AllRequirements",
      storybookUrl: "http://127.0.0.1:6007/?path=/story/harness-requirements-requirementboard--all-requirements",
    },
    {
      kind: "Story",
      name: "RequirementBoard DetailNavigation",
      status: "검토 가능",
      description: "요건 보드에서 요건 ID를 선택해 상세 route로 이동하는 흐름을 Storybook에서 검토하는 상태다.",
      file: "harness/ui/src/features/requirements/RequirementBoard.stories.tsx",
      line: 1,
      storybookTitle: "Harness/Requirements/RequirementBoard",
      storybookStory: "DetailNavigation",
      storybookUrl: "http://127.0.0.1:6007/?path=/story/harness-requirements-requirementboard--detail-navigation",
    },
    {
      kind: "Story",
      name: "RequirementBoard Docs",
      status: "검토 가능",
      description: "요건 보드 Storybook 문서와 검토 설명을 확인하는 Docs 표면이다.",
      file: "harness/ui/src/features/requirements/RequirementBoard.stories.tsx",
      line: 1,
      storybookTitle: "Harness/Requirements/RequirementBoard",
      storybookStory: "Docs",
      storybookUrl: "http://127.0.0.1:6007/?path=/docs/harness-requirements-requirementboard--docs",
    },
  ],
};

// 백엔드 표면(API/DTO/JPA)이 실재하는 앱 요건 대표 fixture. apiSurfaces/dataShapes/entitySurfaces는
// 라이브 buildRequirementDetailModel("application","REQ-022") 출력을 그대로 옮긴 값이며, P3 동치 self-test가
// 라이브와 deep equal을 강제한다. API/DB/소스 탭 스토리는 하네스 요건이 아니라 이 fixture로 검증한다.
export const appRequirementDetail: RequirementDetail = {
  id: "REQ-022",
  title: "할 일 생성",
  cardStatus: "승인",
  priority: "높음",
  targetSystem: "application",
  productArea: "todo",
  verificationLevel: "mixed",
  traceState: "BLUE",
  sourceFile: {
    kind: "card",
    file: "app/docs/requirements/REQ-022-todo-create.md",
    line: 1,
  },
  purpose: "인증 사용자는 제목과 선택 항목으로 자신의 할 일을 생성하고, 생성 결과를 목록에서 바로 확인할 수 있어야 한다.",
  scopeItems: [
    "할 일은 제목이 필수이고 설명, 마감일, 카테고리, 우선순위는 선택 입력이다.",
    "생성된 할 일의 완료 상태는 항상 미완료로 시작한다.",
  ],
  terms: [
    { key: "todo.todo", ko: "할 일", en: "todo" },
    { key: "todo.category", ko: "카테고리", en: "category" },
  ],
  outOfScopeItems: ["반복 할 일, 알림."],
  decisionLogs: [
    {
      date: "2026-06-08",
      decision: "categoryId는 선택 입력이며 미입력 시 미분류 상태로 저장한다.",
      reason: "카테고리 없는 할 일을 허용한다.",
      decisionMaker: "REDSTONE",
      impact: "categoryId 누락과 명시적 null을 모두 미분류로 처리한다.",
    },
  ],
  acceptanceCriteria: [],
  scenarios: [
    {
      title: "인증 사용자가 제목만으로 할 일을 생성한다",
      status: "정의됨",
      file: "app/docs/scenarios/REQ-022-todo-create.feature",
      line: 4,
      covers: [],
      steps: [
        "Given 인증 사용자가 있다",
        "When 제목만으로 할 일 생성을 요청한다",
        "Then 미완료 상태의 할 일이 생성된다",
      ],
    },
  ],
  coverage: [],
  redReasons: [],
  blueBlockedBy: [],
  linkedArtifacts: [
    {
      kind: "scenario",
      file: "app/docs/scenarios/REQ-022-todo-create.feature",
      line: 1,
    },
  ],
  apiSurfaces: [
    {
      method: "POST",
      path: "/todos",
      operationId: "TodoController.createTodo",
      status: "연결됨",
      file: "app/back-end/src/main/java/com/example/bddworkflow/todo/controller/TodoController.java",
      line: 52,
      requests: ["CreateTodoRequest"],
      responses: ["TodoResponse"],
      entities: ["Todo"],
    },
  ],
  dataShapes: [
    {
      kind: "Request",
      name: "CreateTodoRequest",
      status: "연결됨",
      file: "app/back-end/src/main/java/com/example/bddworkflow/todo/dto/CreateTodoRequest.java",
      line: 14,
      fields: [
        { name: "title", type: "String", required: true, description: "할 일 제목 (trim 후 1자 이상 100자 이하)" },
        { name: "description", type: "String", required: false, description: "할 일 설명 (최대 1000자)" },
        { name: "dueDate", type: "LocalDate", required: false, description: "마감일 (YYYY-MM-DD)" },
        { name: "priority", type: "Priority", required: false, description: "우선순위 (HIGH/MEDIUM/LOW, 미입력 시 MEDIUM)" },
        { name: "categoryId", type: "UUID", required: false, description: "본인 소유 카테고리 ID (미입력 또는 null이면 미분류)" },
      ],
    },
    {
      kind: "Response",
      name: "TodoResponse",
      status: "연결됨",
      file: "app/back-end/src/main/java/com/example/bddworkflow/todo/dto/TodoResponse.java",
      line: 13,
      fields: [
        { name: "todoId", type: "UUID", required: false, description: "할 일 식별자" },
        { name: "title", type: "String", required: false, description: "할 일 제목" },
        { name: "description", type: "String", required: false, description: "할 일 설명" },
        { name: "dueDate", type: "LocalDate", required: false, description: "마감일 (YYYY-MM-DD)" },
        { name: "priority", type: "Priority", required: false, description: "우선순위" },
        { name: "completed", type: "boolean", required: false, description: "완료 여부" },
        { name: "category", type: "TodoCategoryInfo", required: false, description: "연결된 카테고리 정보. 연결이 없으면 명시적 null로 직렬화된다." },
      ],
    },
    {
      kind: "Object",
      name: "TodoCategoryInfo",
      status: "연결됨",
      file: "app/back-end/src/main/java/com/example/bddworkflow/todo/dto/TodoCategoryInfo.java",
      line: 9,
      fields: [
        { name: "categoryId", type: "UUID", required: false, description: "카테고리 식별자" },
        { name: "name", type: "String", required: false, description: "카테고리 이름" },
        { name: "color", type: "String", required: false, description: "카테고리 색상" },
      ],
    },
  ],
  entitySurfaces: [
    {
      className: "Todo",
      table: "todo",
      file: "app/back-end/src/main/java/com/example/bddworkflow/todo/domain/Todo.java",
      line: 1,
      listeners: ["AuditingEntityListener"],
      requirements: ["REQ-022", "REQ-023", "REQ-024", "REQ-027", "REQ-025", "REQ-026"],
      columns: [
        {
          fieldName: "id",
          columnName: "id",
          javaType: "UUID",
          primaryKey: true,
          generation: null,
          nullable: null,
          unique: null,
          updatable: null,
          length: null,
          annotations: ["Id", "UuidGenerator", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024", "REQ-027", "REQ-025", "REQ-026"],
        },
        {
          fieldName: "userId",
          columnName: "user_id",
          javaType: "UUID",
          primaryKey: false,
          generation: null,
          nullable: false,
          unique: null,
          updatable: null,
          length: null,
          annotations: ["Requirement", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024", "REQ-027", "REQ-025", "REQ-026"],
        },
        {
          fieldName: "title",
          columnName: "title",
          javaType: "String",
          primaryKey: false,
          generation: null,
          nullable: false,
          unique: null,
          updatable: null,
          length: 100,
          annotations: ["Requirement", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024"],
        },
        {
          fieldName: "description",
          columnName: "description",
          javaType: "String",
          primaryKey: false,
          generation: null,
          nullable: null,
          unique: null,
          updatable: null,
          length: 1000,
          annotations: ["Requirement", "Column"],
          requirements: ["REQ-022", "REQ-024"],
        },
        {
          fieldName: "dueDate",
          columnName: "due_date",
          javaType: "LocalDate",
          primaryKey: false,
          generation: null,
          nullable: null,
          unique: null,
          updatable: null,
          length: null,
          annotations: ["Requirement", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024"],
        },
        {
          fieldName: "priority",
          columnName: "priority",
          javaType: "Priority",
          primaryKey: false,
          generation: null,
          nullable: false,
          unique: null,
          updatable: null,
          length: 10,
          annotations: ["Requirement", "Enumerated", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024"],
        },
        {
          fieldName: "completed",
          columnName: "completed",
          javaType: "boolean",
          primaryKey: false,
          generation: null,
          nullable: false,
          unique: null,
          updatable: null,
          length: null,
          annotations: ["Requirement", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024", "REQ-027"],
        },
        {
          fieldName: "categoryId",
          columnName: "category_id",
          javaType: "UUID",
          primaryKey: false,
          generation: null,
          nullable: null,
          unique: null,
          updatable: null,
          length: null,
          annotations: ["Requirement", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024", "REQ-026"],
        },
        {
          fieldName: "createdAt",
          columnName: "created_at",
          javaType: "Instant",
          primaryKey: false,
          generation: null,
          nullable: false,
          unique: null,
          updatable: false,
          length: null,
          annotations: ["Requirement", "CreatedDate", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024", "REQ-025", "REQ-026"],
        },
        {
          fieldName: "updatedAt",
          columnName: "updated_at",
          javaType: "Instant",
          primaryKey: false,
          generation: null,
          nullable: false,
          unique: null,
          updatable: null,
          length: null,
          annotations: ["Requirement", "LastModifiedDate", "Column"],
          requirements: ["REQ-022", "REQ-023", "REQ-024", "REQ-027", "REQ-025", "REQ-026"],
        },
      ],
    },
  ],
  uiSurfaces: [
    {
      kind: "Page",
      name: "TodoCreateDialog",
      route: "/todos",
      status: "연결됨",
      description: "할 일 생성 입력 대화상자 화면 표면이다.",
      file: "app/front-end/src/features/todos/TodoCreateDialog.tsx",
      line: 1,
    },
    {
      kind: "Story",
      name: "TodoCreateDialog",
      status: "검토 가능",
      description: "할 일 생성 대화상자 UI 설계를 Storybook에서 검토하는 상태다.",
      file: "app/front-end/src/features/todos/TodoCreateDialog.stories.tsx",
      line: 1,
      storybookTitle: "App/Todos/TodoCreateDialog",
      storybookStory: "Default",
      storybookUrl: "http://127.0.0.1:6006/?path=/story/app-todos-todocreatedialog--default",
    },
  ],
};

// 목록 응답 앱 요건 대표 fixture. GET /todos 는 제네릭 envelope PageResponse<TodoResponse>를 반환하므로
// content:List<TodoResponse> 필드와 중첩 DTO 펼침을 Storybook에서 검토할 수 있다. 백엔드 표면은 라이브
// buildRequirementDetailModel("application","REQ-023") 출력과 같으며 parity self-test가 deep equal을 강제한다.
// TodoResponse·TodoCategoryInfo·엔티티 컬럼은 REQ-022 fixture에서 파생한다(REQ-023 은 description 컬럼 제외).
export const appRequirementListDetail: RequirementDetail = {
  ...appRequirementDetail,
  id: "REQ-023",
  title: "할 일 목록 조회",
  purpose: "인증 사용자는 자신의 할 일을 페이지 단위로 조회할 수 있어야 한다.",
  sourceFile: {
    kind: "card",
    file: "app/docs/requirements/REQ-023-todo-list.md",
    line: 1,
  },
  scopeItems: [
    "할 일 목록은 본인 소유 항목만 페이지 단위로 반환한다.",
    "목록 응답은 페이지 메타(page, size, totalElements, totalPages)를 포함한다.",
  ],
  scenarios: [
    {
      title: "인증 사용자가 자신의 할 일 목록을 조회한다",
      status: "정의됨",
      file: "app/docs/scenarios/REQ-023-todo-list.feature",
      line: 4,
      covers: [],
      steps: [
        "Given 인증 사용자의 할 일이 있다",
        "When 할 일 목록을 요청한다",
        "Then 본인 할 일이 페이지 단위로 반환된다",
      ],
    },
  ],
  linkedArtifacts: [
    {
      kind: "scenario",
      file: "app/docs/scenarios/REQ-023-todo-list.feature",
      line: 1,
    },
  ],
  apiSurfaces: [
    {
      method: "GET",
      path: "/todos",
      operationId: "TodoController.listTodos",
      status: "연결됨",
      file: "app/back-end/src/main/java/com/example/bddworkflow/todo/controller/TodoController.java",
      line: 76,
      requests: [],
      responses: ["PageResponse<TodoResponse>"],
      entities: ["Todo"],
    },
  ],
  dataShapes: [
    {
      kind: "Response",
      name: "PageResponse<TodoResponse>",
      status: "연결됨",
      file: "app/back-end/src/main/java/com/example/bddworkflow/common/PageResponse.java",
      line: 8,
      fields: [
        { name: "content", type: "List<TodoResponse>", required: false, description: "현재 페이지의 항목" },
        { name: "page", type: "int", required: false, description: "0-based page index" },
        { name: "size", type: "int", required: false, description: "페이지 크기" },
        { name: "totalElements", type: "long", required: false, description: "전체 항목 수" },
        { name: "totalPages", type: "int", required: false, description: "전체 페이지 수" },
      ],
    },
    // 목록 응답에서 TodoResponse 는 top-level 응답이 아니라 PageResponse content 가 참조하는 중첩 객체다.
    ...appRequirementDetail.dataShapes
      .filter((shape) => shape.name === "TodoResponse" || shape.name === "TodoCategoryInfo")
      .map((shape) => ({ ...shape, kind: "Object" as const })),
  ],
  entitySurfaces: appRequirementDetail.entitySurfaces.map((entity) => ({
    ...entity,
    columns: entity.columns.filter((column) => column.fieldName !== "description"),
  })),
  uiSurfaces: [
    {
      kind: "Page",
      name: "TodoListView",
      route: "/todos",
      status: "연결됨",
      description: "할 일 목록 화면 표면이다.",
      file: "app/front-end/src/features/todos/TodoListView.tsx",
      line: 1,
    },
    {
      kind: "Story",
      name: "TodoListView",
      status: "검토 가능",
      description: "할 일 목록 UI 설계를 Storybook에서 검토하는 상태다.",
      file: "app/front-end/src/features/todos/TodoListView.stories.tsx",
      line: 1,
      storybookTitle: "App/Todos/TodoListView",
      storybookStory: "Default",
      storybookUrl: "http://127.0.0.1:6006/?path=/story/app-todos-todolistview--default",
    },
  ],
};

export const gateCategories: GateCategory[] = [
  { category: "TRACE", blocked: true, errors: 7, byRuleId: { "TRACE-AC-MISSING": 7 } },
  { category: "CARD", blocked: false, errors: 0, byRuleId: {} },
  { category: "REF", blocked: false, errors: 0, byRuleId: {} },
  { category: "TRC", blocked: false, errors: 0, byRuleId: {} },
  { category: "BE", blocked: false, errors: 0, byRuleId: {} },
  { category: "FE", blocked: false, errors: 0, byRuleId: {} },
  { category: "SCN", blocked: false, errors: 0, byRuleId: {} },
  { category: "TRM", blocked: false, errors: 0, byRuleId: {} },
];

export const findingRows = requirementDetail.redReasons;

export const changeSetRows: ChangeSetRow[] = [
  {
    title: "2026-06-10 하네스 로컬 웹 UI MVP",
    status: "진행중",
    requestedDate: "2026-06-10",
    affectedRequirements: requirementRows.slice(0, 3),
    summary: "하네스 산출물을 로컬 웹 UI에서 조회하고 검증 명령을 실행한다.",
    scopeItems: ["하네스 UI 요건", "UI 설계 검토", "검증 명령 실행"],
    completionCriteria: ["REQ-029~REQ-035 승인", "npm run harness:validate 통과"],
    verificationCommands: ["npm run harness:trace -- --requirement REQ-031", "npm run harness:validate"],
    openDiscussions: [],
  },
];

export const commands: CommandDefinition[] = [
  { id: "harness:trace", label: "Harness Trace", description: "하네스 범위 추적 산출물을 갱신한다.", supportsRequirement: true },
  { id: "harness:validate", label: "Harness Validate", description: "하네스 게이트를 실행한다.", supportsRequirement: false },
  { id: "harness:self-test", label: "Harness Self Test", description: "하네스 self-test를 실행한다.", supportsRequirement: false },
  { id: "app:trace", label: "App Trace", description: "애플리케이션 범위 추적 산출물을 갱신한다.", supportsRequirement: true },
  { id: "app:validate", label: "App Validate", description: "애플리케이션 게이트를 실행한다.", supportsRequirement: false },
  { id: "repo:validate", label: "Repo Validate", description: "두 범위 게이트를 순차 실행한다.", supportsRequirement: false },
];

export const readyRun: CommandRunState = {
  status: "ready",
  selectedCommand: "harness:trace",
  logs: [],
};

export const runningRun: CommandRunState = {
  ...readyRun,
  status: "running",
  requirementId: "REQ-031",
  startedAt: "2026-06-10T14:30:00.000Z",
  logs: ["[harness:index-requirements] requirements.index.json", "[harness:trace] trace-requirements.mjs --requirement REQ-031"],
};

export const succeededRun: CommandRunState = {
  ...runningRun,
  status: "succeeded",
  exitCode: 0,
  logs: [...runningRun.logs, "gate: pass"],
};

export const failedRun: CommandRunState = {
  ...runningRun,
  status: "failed",
  exitCode: 1,
  logs: [...runningRun.logs, "TRACE failed: REQ-031 RED"],
};

export const rejectedRun: CommandRunState = {
  ...readyRun,
  status: "rejected",
  selectedCommand: "npm:arbitrary",
  rejectionReason: "허용 목록 밖 명령이다.",
};
